# Generated by Django 4.2.1 on 2023-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField()),
                ('type_of_coverage', models.CharField(max_length=10)),
                ('start', models.TimeField(null=True)),
                ('end', models.TimeField(null=True)),
            ],
        ),
    ]
