# Generated by Django 4.2.1 on 2023-05-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_shiftadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftadjustment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shiftadjustment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
            preserve_default=False,
        ),
    ]
