# Generated by Django 4.2.1 on 2023-05-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_shiftadjustment_date_shiftadjustment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftadjustment',
            name='employee',
            field=models.CharField(max_length=30),
        ),
    ]
