# Generated by Django 4.2.1 on 2023-05-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_shiftadjustment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftadjustment',
            name='approved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
