# Generated by Django 4.2.1 on 2023-05-25 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_shiftadjustment_shift_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftadjustment',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.shift'),
        ),
    ]
