# Generated by Django 4.2.1 on 2023-05-26 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_shiftadjustment_user_alter_shiftadjustment_shift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftadjustment',
            unique_together={('user', 'start', 'end', 'date')},
        ),
    ]
