# Generated by Django 4.2.1 on 2023-05-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_shiftadjustment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(null=True)),
                ('end', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('open', models.BooleanField()),
            ],
        ),
    ]
