# Generated by Django 4.2.1 on 2023-05-07 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_shift_day_shift_date_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
