# Generated by Django 4.2.1 on 2023-05-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='color',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
