# Generated by Django 4.2.1 on 2023-05-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_shiftadjustment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftadjustment',
            name='shift_id',
        ),
        migrations.AddField(
            model_name='shiftadjustment',
            name='shift',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.shift'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('student', 'start_time', 'end_time', 'date')},
        ),
    ]
